"use client";

import { FormEvent, useEffect, useState } from "react";
import type { InviteKey, Profile } from "@/types/database";

type AdminUser = Pick<Profile, "id" | "username" | "display_name" | "role" | "created_at"> & { status: string };
export function AdminDashboard() {
  const [users, setUsers] = useState<AdminUser[]>([]); const [invites, setInvites] = useState<InviteKey[]>([]); const [key, setKey] = useState(""); const [role, setRole] = useState("user"); const [maxUses, setMaxUses] = useState("1"); const [expiresAt, setExpiresAt] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  async function load() { const [userResponse, inviteResponse] = await Promise.all([fetch("/api/admin/users"), fetch("/api/admin/invites")]); const userData = await userResponse.json(); const inviteData = await inviteResponse.json(); if (userResponse.ok) setUsers(userData.users ?? []); if (inviteResponse.ok) setInvites(inviteData.invites ?? []); }
  useEffect(() => { void load(); }, []);
  async function createInvite(event: FormEvent) { event.preventDefault(); setError(""); setMessage(""); const response = await fetch("/api/admin/invites", {method:"POST", headers:{"Content-Type":"application/json"}, body:JSON.stringify({key, role, maxUses:Number(maxUses), expiresAt:expiresAt ? new Date(expiresAt).toISOString() : null})}); const data = await response.json(); if (!response.ok) setError(data.error ?? "สร้าง invite key ไม่สำเร็จ"); else { setMessage("สร้าง invite key แล้ว"); setKey(""); await load(); } }
  async function userAction(userId: string, action: string, userRole?: string) { const response = await fetch("/api/admin/users", {method:"PATCH", headers:{"Content-Type":"application/json"}, body:JSON.stringify({userId, action, role:userRole})}); const data = await response.json(); if (!response.ok) setError(data.error ?? "ทำรายการไม่สำเร็จ"); else await load(); }
  async function disableInvite(id: string, disabled: boolean) { await fetch("/api/admin/invites", {method:"PATCH", headers:{"Content-Type":"application/json"}, body:JSON.stringify({id, disabled})}); await load(); }
  return <div className="admin-grid"><section className="panel"><h3>สร้าง invite key</h3><p>สร้าง key สำหรับผู้ใช้ใหม่ โดยกำหนด role และจำนวนครั้งที่ใช้ได้</p><form onSubmit={createInvite}><div className="field"><label>Key</label><input value={key} onChange={(e) => setKey(e.target.value)} required /></div><div className="field"><label>Role</label><select value={role} onChange={(e) => setRole(e.target.value)}><option value="user">user</option><option value="admin">admin</option></select></div><div className="field"><label>Max uses</label><input type="number" min="1" max="1000" value={maxUses} onChange={(e) => setMaxUses(e.target.value)} required /></div><div className="field"><label>หมดอายุ (ไม่บังคับ)</label><input type="datetime-local" value={expiresAt} onChange={(e) => setExpiresAt(e.target.value)} /></div><button className="primary-button">สร้าง key</button></form>{message && <p className="form-success" style={{marginTop:12}}>{message}</p>}{error && <p className="form-error" style={{marginTop:12}}>{error}</p>}</section><section className="panel"><h3>Invite keys</h3><div className="admin-table-wrap"><table><thead><tr><th>Key</th><th>Role</th><th>Uses</th><th>Status</th><th /></tr></thead><tbody>{invites.map((invite) => { const disabled = Boolean(invite.disabled_at) || invite.used_count >= invite.max_uses || Boolean(invite.expires_at && new Date(invite.expires_at) <= new Date()); return <tr key={invite.id}><td>{invite.key}</td><td>{invite.role}</td><td>{invite.used_count}/{invite.max_uses}</td><td><span className={`status ${disabled ? "disabled" : ""}`}>{disabled ? "disabled" : "active"}</span></td><td><button className="admin-actions" onClick={() => disableInvite(invite.id, !invite.disabled_at)}>{invite.disabled_at ? "เปิดใช้" : "ปิดใช้"}</button></td></tr>; })}</tbody></table></div></section><section className="panel" style={{gridColumn:"1 / -1"}}><h3>ผู้ใช้ทั้งหมด</h3><div className="admin-table-wrap"><table><thead><tr><th>Username</th><th>ชื่อที่แสดง</th><th>Role</th><th>สถานะ</th><th>สร้างเมื่อ</th><th>จัดการ</th></tr></thead><tbody>{users.map((user) => <tr key={user.id}><td>@{user.username}</td><td>{user.display_name}</td><td>{user.role}</td><td><span className={`status ${user.status === "disabled" ? "disabled" : ""}`}>{user.status}</span></td><td>{new Date(user.created_at).toLocaleDateString("th-TH")}</td><td><div className="admin-actions"><button onClick={() => userAction(user.id, user.status === "disabled" ? "enable" : "disable")}>{user.status === "disabled" ? "เปิดใช้" : "ปิดใช้"}</button><button onClick={() => userAction(user.id, "role", user.role === "admin" ? "user" : "admin")}>{user.role === "admin" ? "ลดเป็น user" : "ตั้งเป็น admin"}</button><button className="danger-button" onClick={() => userAction(user.id, "delete")}>ลบ</button></div></td></tr>)}</tbody></table></div></section></div>;
}
